Menu = HadesLocation.New("Menu")

Tartarus = HadesLocation.New("Tartarus")
Megaera = HadesLocation.New("Megaera")
Asphodel = HadesLocation.New("Asphodel")
Lernie = HadesLocation.New("Lernie")
Elysium = HadesLocation.New("Elysium")
Besties = HadesLocation.New("Besties")
Styx = HadesLocation.New("Styx")
StyxLate = HadesLocation.New("StyxLate")
HadesBoss = HadesLocation.New("HadesBoss")
Goal = HadesLocation.New("Goal")

DivinePairings = HadesBoss.New("DivinePairings")

AphroditeKeepsake = HadesLocation.New("AphroditeKeepsake")
AresKeepsake = HadesLocation.New("AresKeepsake")
ArtemisKeepsake = HadesLocation.New("ArtemisKeepsake")
AthenaKeepsake = HadesLocation.New("AthenaKeepsake")
ChaosKeepsake = HadesLocation.New("ChaosKeepsake")
DemeterKeepsake = HadesLocation.New("DemeterKeepsake")
DionysusKeepsake = HadesLocation.New("DionysusKeepsake")
EurydiceKeepsake = HadesLocation.New("EurydiceKeepsake")
HermesKeepsake = HadesLocation.New("HermesKeepsake")
PatroclusKeepsake = HadesLocation.New("PatroclusKeepsake")
PoseidonKeepsake = HadesLocation.New("PoseidonKeepsake")
ThanatosKeepsake = HadesLocation.New("ThanatosKeepsake")
ZeusKeepsake = HadesLocation.New("ZeusKeepsake")